# fly.toml app configuration file generated for restless-frog-3500 on 2023-09-29T19:59:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restless-frog-3500"
primary_region = "yul"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
